project:
  type: website
  output-dir: docs


  
website:
  
  title: ""
  
  favicon: pasaporte.png.png #opcion para enlacs dentro de redes sociales
  image: pasaporte.png.png #opcion para enlacs dentro de redes sociales
  twitter-card: true #opcion para enlacs dentro de twitter
  open-graph: true
  
  cookie-consent:
    type: implied
    style: interstitial
    palette: light
    language: spanish
  google-analytics:
    tracking-id: "G-YLKB5451TC" #primero crear la cta de google analiticas 
    anonymize-ip: true
    
  navbar:
    logo: pasaporte.png.png
    
    left:
      - text: bienvenido
        href: index.qmd
      - text: beneficios
        href: projects.qmd
      - text: pasaporte
        href: pasaporte.qmd
      - text: inversi칩n
        href: inversi칩n.qmd
      - text: contacto
        href: contacto.qmd
      - text: blog
        href: blog.qmd
    tools:
      - icon: linkedin
        href: https://linkedin.com/in/치ngel-moreta-y치nez-mba-msc-38aa898b
      - icon: instagram
        href: https://www.instagram.com/mesias_moreta/
  
  page-footer:
  
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Angel Moreta"

    center: 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
      - text: "Trademark"
        href: trademark.qmd
    border: false
    background: dark
    foreground: white
    
format:
  html:
    theme:    
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    toc: true

editor: source

