project:
  type: website
  output-dir: docs
  
website:
  title: "Golden Visa Española"
  navbar:
    left:
      - href: index.qmd
        text: ¡Bienvenido!
      - projects.qmd
      - text: blog
        href: blog.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/mesiasmoreta/gvisa
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Angel Moreta"

format:
  html:
    theme: minty
    toc: true

editor: source

