---
title: "aviso_legal"
---
En cumplimiento del artículo 10 de la Ley 34/2002, de 1 de julio, de Servicios de la Sociedad de la Información y Comercio Electrónico (LSSI-CE), se informa al usuario la siguiente información:

Denominación social y titular de la web: RAIMUNDO MARTINEZ BENEDITO Nombre comercial: RTG FINANCE

NIF: 26013677-X
Domicilio social: Angel Guimera, 40 Pta. 3 Valencia Dirección de correo electrónico: hipotecas@rtgfinance.com Dirección web: www.rtgfinance.com 

 

1.    INFORMACIÓN LEGAL
Bienvenido al Sitio Web RTG FINANCE el cual ha sido diseñado con el objeto de facilitarle información general acerca de la actividad y los servicios que ofrece.

RTG FINANCE tiene como objeto social la realización de diversas actividades en el mercado financiero, inmobiliario, entre ellas, la solicitud, intermediación y obtención de todo tipo de préstamos y créditos.

Los términos y condiciones que serán aplicables durante su navegación por este Sitio Web se encuentran recogidos en el apartado “Condiciones Generales de Uso” del presente documento, de conformidad con la normativa legal vigente. Se recuerda que el responsable podría modificar en cualquier momento estas condiciones de manera unilateral, por lo que es recomendable que las visite de forma periódica a fin de estar debidamente informado de posibles cambios realizados.

El acceso al Sitio Web es gratuito, salvo en lo relativo al coste de la conexión a través de la red de telecomunicaciones suministrada por el proveedor de acceso contratado por los usuarios. La utilización del Sitio Web le atribuye la condición de Usuario e implica la aceptación de todas las condiciones incluidas en este Aviso Legal.

Para garantizar que su navegación se ajuste a los criterios de transparencia, claridad y sencillez, se informa al Usuario de que cualquier duda, sugerencia o consulta sobre el presente Aviso Legal será recibida y tramitada a través de la dirección de correo electrónico hipotecas@rtgfinance.com

 

2.    CONDICIONES GENERALES DE USO
COMPROMISOS Y OBLIGACIONES DEL USUARIO
El usuario se compromete a utilizar los servicios y contenidos del Sitio Web, de conformidad con la legislación aplicable y las presentes Condiciones Generales de Uso, así como con demás condiciones, reglamentos o instrucciones que en su caso pudieran resultar de aplicación en el presente Aviso Legal.

El Usuario responderá frente a RTG FINANCE o frente a terceros de cualesquiera daños y perjuicios que pudieran causarse como consecuencia del incumplimiento de esta obligación.

Queda expresamente prohibido el uso del Sitio Web con fines lesivos de bienes o intereses del responsable o de terceros o que de cualquier otra forma sobrecarguen, dañen o inutilicen las redes, servidores y demás equipos informáticos (hardware) o productos y aplicaciones informáticas (software) de los mismos.

 

2.2  EXCLUSIÓN DE RESPONSABILIDAD
RTG FINANCE no se responsabiliza ni garantiza que el acceso a este Sitio Web esté libre de error o no pueda ser interrumpido por eventuales errores de programación u otras causas de fuerza mayor.

El titular adopta medidas de seguridad razonablemente adecuadas para detectar la existencia de virus. No obstante, dado que las medidas de seguridad de los sistemas informáticos no son plenamente fiables, no se garantiza la ausencia de virus ni de otros elementos en los contenidos que puedan producir alteraciones en su sistema informático (software y hardware)

o en los documentos electrónicos y ficheros almacenados en su sistema informático, por lo que corresponde al Usuario disponer de herramientas adecuadas para su detección.

De igual manera, en ningún caso será responsable por las pérdidas, daños o perjuicios de cualquier naturaleza, directos o indirectos, que surjan por el acceso y uso del Sitio Web o sus contenidos, ni por aquellos que pudiesen ocasionarse al Usuario por un uso inadecuado de este Sitio Web o sus contenidos. En particular, no se responsabiliza en modo alguno de las caídas, interrupciones, falta o defecto de las comunicaciones ni de los daños informáticos que pudieran ocasionar al usuario visitante el acceso a los contenidos de este sitio.

 

2.3  ENLACES EXTERNOS
Este Sitio Web proporciona enlaces a sitios webs de terceros que permiten al Usuario ser redirigido. El responsable no asume ningún tipo de responsabilidad respecto a los contenidos que pudieran albergar.

En caso de advertir la existencia de contenidos contrarios a la ley, la moral o el orden público, el responsable procederá a la retirada inmediata del enlace a la web en cuestión y a la comunicación de esta situación a la autoridad competente, conforme al artículo 16 de la Ley 34/2002, de 11 de julio, de servicios de la sociedad de la información y de comercio electrónico (LSSICE). Esta circunstancia se extiende a la información y contenidos alojados en foros, chats, comentarios, redes sociales, blogs y similares.

 

3.    PROTECCIÓN DE DATOS PERSONALES
La información sobre el tratamiento de sus datos personales se encuentra detallada en la Política de Privacidad.

 

4.    PROPIEDAD INDUSTRIAL E INTELECTUAL
Todos los contenidos del Sitio Web –entendiendo como tales a título meramente enunciativo pero no limitativo los textos, fotografías, gráficos, iconos, tecnología, software, links y demás contenidos audiovisuales o sonoros, así como su diseño gráfico y códigos fuente (en adelante, los

“Contenidos”) –son propiedad intelectual de RTG FINANCE, sin que puedan entenderse cedidos al Usuario ninguno de los derechos de explotación sobre los mismos más allá de lo estrictamente necesario para el correcto uso del Sitio. Asimismo, todas las marcas, nombres comerciales, logos y signos distintivos son propiedad de RTG FINANCE y no podrán ser reproducidos o utilizados por el Usuario salvo autorización expresa otorgada por él.

El Usuario se compromete a no reproducir, copiar, distribuir, poner a disposición o comunicar públicamente de cualquier otro modo, transformar o modificar los Contenidos salvo en los casos autorizados por la ley o consentidos de forma expresa por RTG FINANCE o, en su caso, por quien ostente la titularidad de los derechos de explotación. El acceso al Sitio Web no implica bajo ninguna circunstancia ningún tipo de renuncia, transmisión, licencia o cesión total ni parcial de dichos derechos, salvo que se establezca expresamente lo contrario.

El Usuario deberá abstenerse de reproducir o copiar para uso privado los Contenidos que puedan ser considerados como Software o Base de Datos de conformidad con la legislación vigente en materia de propiedad intelectual, así como su comunicación pública o puesta a disposición de terceros cuando estos actos impliquen necesariamente la reproducción por parte del Usuario o de un tercero.

 

5.    MAYORIA DE EDAD
La utilización de la Página Web de www.rtgfinance.com, no está dirigida a menores de 14 años y, por consiguiente, éstos deberán abstenerse de facilitar cualquier información de carácter personal. En este sentido, RTG FINANCE. recomienda la utilización de su Página Web a personas mayores de 18 años. Para ello, RTG FINANCE, se reserva el derecho a comprobar en cualquier momento la edad de los usuarios de su Página Web.

 

6.    LEY APLICABLE
La ley aplicable en caso de disputa o conflicto de interpretación de los términos y condiciones de este Sitio Web, así como cualquier cuestión relacionada con los servicios ofertados en el mismo, será la ley española.
